name: deepl_dart
description: Dart library for the DeepL language translation API. 
version: 0.1.0
homepage: https://github.com/komape/deepl_dart
repository: https://github.com/komape/deepl_dart
issue_tracker: https://github.com/komape/deepl_dart/issues

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
